### ISSUE TITLE
Изменить формат основной страницы

### ISSUE THREAD

**Issue by dos65** [scalalaz-podcast/scalalaz-gen#2]
Сейчас у нас просто ссылки сбоку, нужно основная страница с превьюхами страниц эпизодов, страниц для тем и ссылками на них(ну и наверное pagination нужно сделать)

**Comment by strobe** [comment]
для интерисующихся, работа ведется тут https://github.com/scalalaz-podcast/scalalaz-gen/commits/wip-list-of-issues

**Comment by dos65** [comment]
done in #10
