### ISSUE TITLE
Проблемы с RSS 

### ISSUE THREAD

**Issue by IRus** [scalalaz-podcast/scalalaz-gen#7]
- [ ] Ссылки всегда ведут на главную
- [ ] Body содержит маркдаун, а не html

**Comment by dos65** [comment]
@IRus спасибо за репорт.
А чем ты пользуешься для просмотра rss? Я проверил через QuiteRss - ссылки ведут на страницы выпуска.

С маркдауном в теле поинтресенее, оперативно не поправить)

**Comment by IRus** [comment]
Tiny Tiny RSS, я подозреваю что вам не хватает тэга линк https://github.com/IRus/read-it-later/blob/master/docs/feed.xml#L16

Ну и стандарты конечно подскажут http://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fscalalaz.ru%2Frss%2Ffeed.xml

**Comment by IRus** [comment]
для markdown хотя бы заверните его там pre/code, иначе ридер считает что это html и у меня портянка текста без пробелов, вместо шоунотов

**Comment by dos65** [comment]
@IRus  спасибо за предложение с `pre`. линки добавил

**Comment by IRus** [comment]
@dos65 аттрибуты в RSS case-sensetive, так что нужно еще поправить `isPermaLink`

**Comment by IRus** [comment]
@dos65 спасибо, проверил фид - ссылки теперь работают, читать шоуноты можно
